AllCops:
  Exclude:
    - 'app/admin/*'
    - 'db/migrate/*'
    - 'bin/*'
    - 'config/puma.rb'
    - 'config/spring.rb'
    - 'db/*'
    - 'config/routes.rb'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'config/application.rb'
    - 'Gemfile'
Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Metrics/AbcSize:
  Max: 20
Metrics/LineLength:
  Max: 90
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - 'app/admin/**/*'
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/DateTime:
  Enabled: false