# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Manager.create!(email:'henry2992@hotmail.com', password:'test1234', password_confirmation:'test1234')

Config.create!(id: 1, key:'cancelation_penalty_time', description:'Horas para cancelar un trabajo', value: '2')
Config.create!(id: 2, key:'cancelation_penalty_amount', description:'valor de penalización de NocNoc', value: '5')
Config.create!(id: 3, key:'noc_noc_service_fee', description:'Pago fee de NocNoc', value: '25')


limpieza_de_hogar = ServiceType.create!(name:'Limpieza de Hogar')
jardineria = ServiceType.create!(name:'Jardineria')


Service.create!(service_type: limpieza_de_hogar, type_service: 'addon',  name: 'Cocinado', quantity: false, time: 1.5, price: 5.0)
Service.create!(service_type: limpieza_de_hogar, type_service: 'base',  name: 'Cocinado', quantity: false, time: 1.5, price: 5.0)
Service.create!(service_type: limpieza_de_hogar, type_service: 'parameter',  name: 'Habitaciones', quantity: true, time: 0.5, price: 5.0)
Service.create!(service_type: limpieza_de_hogar, type_service: 'addon',  name: 'Lavado de Refrigerador', quantity: false, time: 1.5, price: 5.0)
Service.create!(service_type: jardineria, type_service: 'base',  name: 'Jardineria', quantity: false, time: 1.5, price: 3.0)
Service.create!(service_type: jardineria, type_service: 'parameter',  name: 'Patio', quantity: true, time: 1.5, price: 4.0)
Service.create!(service_type: limpieza_de_hogar, type_service: 'addon',  name: 'Planchado', quantity: false, time: 1.5, price: 5.0)
Service.create!(service_type: limpieza_de_hogar, type_service: 'parameter',  name: 'Baños', quantity: true, time: 0.5, price: 5.0)

quito = City.create!(name: 'Quito')


Neightborhood.create!(city: quito, name: '1RA ZONA AEREA'.titleize)
Neightborhood.create!(city: quito, name: '2 DE FEBRERO'.titleize)
Neightborhood.create!(city: quito, name: '20 DE MAYO'.titleize)
Neightborhood.create!(city: quito, name: '24 DE JUNIO'.titleize)
Neightborhood.create!(city: quito, name: '6 DE DICIEMBRE'.titleize)
Neightborhood.create!(city: quito, name: 'AGUA CLARA'.titleize)
Neightborhood.create!(city: quito, name: 'ALEGRIA N 1'.titleize)
Neightborhood.create!(city: quito, name: 'ALVARO PEREZ IND'.titleize)
Neightborhood.create!(city: quito, name: 'AMAZONAS'.titleize)
Neightborhood.create!(city: quito, name: 'AMERICA'.titleize)
Neightborhood.create!(city: quito, name: 'ANA LUISA'.titleize)
Neightborhood.create!(city: quito, name: 'AREA DE PROTECCIÓN'.titleize)
Neightborhood.create!(city: quito, name: 'AREA VERDE'.titleize)
Neightborhood.create!(city: quito, name: 'ARGENTINA'.titleize)
Neightborhood.create!(city: quito, name: 'ATAHUALPA'.titleize)
Neightborhood.create!(city: quito, name: 'AVIACION CIVIL'.titleize)
Neightborhood.create!(city: quito, name: 'BARRIO CENTRAL C'.titleize)
Neightborhood.create!(city: quito, name: 'BARRIONUEVO'.titleize)
Neightborhood.create!(city: quito, name: 'BATAN ALTO'.titleize)
Neightborhood.create!(city: quito, name: 'BATAN BAJO'.titleize)
Neightborhood.create!(city: quito, name: 'BELLAVISTA'.titleize)
Neightborhood.create!(city: quito, name: 'BELLAVISTA ALTA'.titleize)
Neightborhood.create!(city: quito, name: 'BILOXI'.titleize)
Neightborhood.create!(city: quito, name: 'CALZADO 1 MAYO'.titleize)
Neightborhood.create!(city: quito, name: 'CAMINOS  LIBERTA'.titleize)
Neightborhood.create!(city: quito, name: 'CARCELEN BAJO'.titleize)
Neightborhood.create!(city: quito, name: 'CARCELEN BEV'.titleize)
Neightborhood.create!(city: quito, name: 'CASA TUYA'.titleize)
Neightborhood.create!(city: quito, name: 'CAUPICHO I'.titleize)
Neightborhood.create!(city: quito, name: 'CAUSAYLLACTA'.titleize)
Neightborhood.create!(city: quito, name: 'CHAHUARQUINGO'.titleize)
Neightborhood.create!(city: quito, name: 'CHAUPICRUZ'.titleize)
Neightborhood.create!(city: quito, name: 'CHAVEZPAMBA'.titleize)
Neightborhood.create!(city: quito, name: 'CHILLOGALLO'.titleize)
Neightborhood.create!(city: quito, name: 'CHIMBACALLE'.titleize)
Neightborhood.create!(city: quito, name: 'CIUDAD ALEGRIA'.titleize)
Neightborhood.create!(city: quito, name: 'COL. DE MEDICOS'.titleize)
Neightborhood.create!(city: quito, name: 'COLINA PICHINCHA'.titleize)
Neightborhood.create!(city: quito, name: 'COLINAS DEL NORT'.titleize)
Neightborhood.create!(city: quito, name: 'COLINAS DEL SUR'.titleize)
Neightborhood.create!(city: quito, name: 'COMITE DEL PUEBL'.titleize)
Neightborhood.create!(city: quito, name: 'COND. LAS CUADRA'.titleize)
Neightborhood.create!(city: quito, name: 'CONSEJO PROVINCI'.titleize)
Neightborhood.create!(city: quito, name: 'CORAZON DE JESUS'.titleize)
Neightborhood.create!(city: quito, name: 'CORPUS CRISTI'.titleize)
Neightborhood.create!(city: quito, name: 'COTOCOLLAO'.titleize)
Neightborhood.create!(city: quito, name: 'CUARTEL M SUCRE'.titleize)
Neightborhood.create!(city: quito, name: 'DAMMER'.titleize)
Neightborhood.create!(city: quito, name: 'DAMMER 1'.titleize)
Neightborhood.create!(city: quito, name: 'DAMMER 2'.titleize)
Neightborhood.create!(city: quito, name: 'DOS PUENTES'.titleize)
Neightborhood.create!(city: quito, name: 'ECUADOR'.titleize)
Neightborhood.create!(city: quito, name: 'EJERCITO NACIONA'.titleize)
Neightborhood.create!(city: quito, name: 'EJIDO'.titleize)
Neightborhood.create!(city: quito, name: 'EL CALVARIO'.titleize)
Neightborhood.create!(city: quito, name: 'EL CAMAL'.titleize)
Neightborhood.create!(city: quito, name: 'EL CARMEN'.titleize)
Neightborhood.create!(city: quito, name: 'EL CONDE I'.titleize)
Neightborhood.create!(city: quito, name: 'EL EDEN'.titleize)
Neightborhood.create!(city: quito, name: 'EL GUABO'.titleize)
Neightborhood.create!(city: quito, name: 'EL INCA'.titleize)
Neightborhood.create!(city: quito, name: 'EL PARAISO'.titleize)
Neightborhood.create!(city: quito, name: 'EL PORVENIR'.titleize)
Neightborhood.create!(city: quito, name: 'EL ROCIO'.titleize)
Neightborhood.create!(city: quito, name: 'EL ROCIO GUAMANI'.titleize)
Neightborhood.create!(city: quito, name: 'EL ROSARIO'.titleize)
Neightborhood.create!(city: quito, name: 'EL TRANSITO'.titleize)
Neightborhood.create!(city: quito, name: 'ETERNIT'.titleize)
Neightborhood.create!(city: quito, name: 'EUCALIPTOS VALLE'.titleize)
Neightborhood.create!(city: quito, name: 'EUGENIO ESPEJO'.titleize)
Neightborhood.create!(city: quito, name: 'FELIXRIVADENEIRA'.titleize)
Neightborhood.create!(city: quito, name: 'FERROVIARIA MEDI'.titleize)
Neightborhood.create!(city: quito, name: 'FORESTAL MEDIA'.titleize)
Neightborhood.create!(city: quito, name: 'FRANKLIN TELLO'.titleize)
Neightborhood.create!(city: quito, name: 'GONZALES SUAREZ'.titleize)
Neightborhood.create!(city: quito, name: 'GUAJALO'.titleize)
Neightborhood.create!(city: quito, name: 'GUALEA'.titleize)
Neightborhood.create!(city: quito, name: 'HDA GUAPULO'.titleize)
Neightborhood.create!(city: quito, name: 'HERMANO MIGUEL'.titleize)
Neightborhood.create!(city: quito, name: 'HEROES PAQUISHA'.titleize)
Neightborhood.create!(city: quito, name: 'HOGAR  ANCIANOS'.titleize)
Neightborhood.create!(city: quito, name: 'HOSPITAL SOLCA'.titleize)
Neightborhood.create!(city: quito, name: 'HOSPITALARI 2ETP'.titleize)
Neightborhood.create!(city: quito, name: 'HUAYRALLACTA'.titleize)
Neightborhood.create!(city: quito, name: 'I¦AQUITO ALTO'.titleize)
Neightborhood.create!(city: quito, name: 'JARDIN DEL VALLE'.titleize)
Neightborhood.create!(city: quito, name: 'JARDINES DEL BAT'.titleize)
Neightborhood.create!(city: quito, name: 'JOSE TERAN'.titleize)
Neightborhood.create!(city: quito, name: 'JULIO MATOVELLE'.titleize)
Neightborhood.create!(city: quito, name: 'JULIO MORENO D.'.titleize)
Neightborhood.create!(city: quito, name: 'JULIO ZABALA'.titleize)
Neightborhood.create!(city: quito, name: 'LA ALAMEDA'.titleize)
Neightborhood.create!(city: quito, name: 'LA BOTA'.titleize)
Neightborhood.create!(city: quito, name: 'LA CANTERA'.titleize)
Neightborhood.create!(city: quito, name: 'LA CAROLINA'.titleize)
Neightborhood.create!(city: quito, name: 'LA CERAMICA'.titleize)
Neightborhood.create!(city: quito, name: 'LA CHILENA'.titleize)
Neightborhood.create!(city: quito, name: 'LA COLON'.titleize)
Neightborhood.create!(city: quito, name: 'LA FLORENCIA'.titleize)
Neightborhood.create!(city: quito, name: 'LA FLORIDA'.titleize)
Neightborhood.create!(city: quito, name: 'LA GRANJA'.titleize)
Neightborhood.create!(city: quito, name: 'LA INDEPENDENCIA'.titleize)
Neightborhood.create!(city: quito, name: 'LA ISLA'.titleize)
Neightborhood.create!(city: quito, name: 'LA JOSEFINA'.titleize)
Neightborhood.create!(city: quito, name: 'LA KENNEDY'.titleize)
Neightborhood.create!(city: quito, name: 'LA LIBERTAD BAJO'.titleize)
Neightborhood.create!(city: quito, name: 'LA MERCED'.titleize)
Neightborhood.create!(city: quito, name: 'LA PERLA'.titleize)
Neightborhood.create!(city: quito, name: 'LA RAYA A'.titleize)
Neightborhood.create!(city: quito, name: 'LA RECOLETA'.titleize)
Neightborhood.create!(city: quito, name: 'LA TOLA'.titleize)
Neightborhood.create!(city: quito, name: 'LA TOLA ALTA'.titleize)
Neightborhood.create!(city: quito, name: 'LA UNION'.titleize)
Neightborhood.create!(city: quito, name: 'LA VICENTINA'.titleize)
Neightborhood.create!(city: quito, name: 'LA VICTORIA'.titleize)
Neightborhood.create!(city: quito, name: 'LAS CUADRAS'.titleize)
Neightborhood.create!(city: quito, name: 'LIBERTAD BAJO'.titleize)
Neightborhood.create!(city: quito, name: 'LIFE'.titleize)
Neightborhood.create!(city: quito, name: 'LLOA'.titleize)
Neightborhood.create!(city: quito, name: 'LOMA HERMOSA'.titleize)
Neightborhood.create!(city: quito, name: 'LOMAS DE CUMBAYA'.titleize)
Neightborhood.create!(city: quito, name: 'LOS ARRAYANES'.titleize)
Neightborhood.create!(city: quito, name: 'LOS ARUPOS'.titleize)
Neightborhood.create!(city: quito, name: 'LOS CIPRESES'.titleize)
Neightborhood.create!(city: quito, name: 'LOS DOS PUENTES'.titleize)
Neightborhood.create!(city: quito, name: 'LOS FAIQUES'.titleize)
Neightborhood.create!(city: quito, name: 'LOS LAURELES'.titleize)
Neightborhood.create!(city: quito, name: 'LOS PEDESTALES'.titleize)
Neightborhood.create!(city: quito, name: 'LOS SHYRIS'.titleize)
Neightborhood.create!(city: quito, name: 'LOTIZ MIRAVALLE'.titleize)
Neightborhood.create!(city: quito, name: 'LUIS A.VALENCIA'.titleize)
Neightborhood.create!(city: quito, name: 'LULUNCOTO'.titleize)
Neightborhood.create!(city: quito, name: 'MADRIGAL'.titleize)
Neightborhood.create!(city: quito, name: 'MARIANA DE JESUS'.titleize)
Neightborhood.create!(city: quito, name: 'MARISCAL AYACUCH'.titleize)
Neightborhood.create!(city: quito, name: 'MEXICO'.titleize)
Neightborhood.create!(city: quito, name: 'MEXTERIOR'.titleize)
Neightborhood.create!(city: quito, name: 'MIRAFLORES'.titleize)
Neightborhood.create!(city: quito, name: 'MIRAFLORES ALTO'.titleize)
Neightborhood.create!(city: quito, name: 'MIRAFLORES BAJO'.titleize)
Neightborhood.create!(city: quito, name: 'MONTESERRIN'.titleize)
Neightborhood.create!(city: quito, name: 'NANEGAL'.titleize)
Neightborhood.create!(city: quito, name: 'NANEGALITO'.titleize)
Neightborhood.create!(city: quito, name: 'NINALLACTA'.titleize)
Neightborhood.create!(city: quito, name: 'NINGUILLA'.titleize)
Neightborhood.create!(city: quito, name: 'NONO'.titleize)
Neightborhood.create!(city: quito, name: 'NTR. MADRE MERCE'.titleize)
Neightborhood.create!(city: quito, name: 'NUEVA VIDA'.titleize)
Neightborhood.create!(city: quito, name: 'PABLO ART SUAREZ'.titleize)
Neightborhood.create!(city: quito, name: 'PACTO'.titleize)
Neightborhood.create!(city: quito, name: 'PALUCO B'.titleize)
Neightborhood.create!(city: quito, name: 'PAMBACHUPA'.titleize)
Neightborhood.create!(city: quito, name: 'PANAMERICA SUR'.titleize)
Neightborhood.create!(city: quito, name: 'PERUCHO'.titleize)
Neightborhood.create!(city: quito, name: 'PIO XII'.titleize)
Neightborhood.create!(city: quito, name: 'PLAN VICTORIA'.titleize)
Neightborhood.create!(city: quito, name: 'PORTAL CUMBAYA 1'.titleize)
Neightborhood.create!(city: quito, name: 'PRESIDENCIA REPU'.titleize)
Neightborhood.create!(city: quito, name: 'PROFES MUNICIPAL'.titleize)
Neightborhood.create!(city: quito, name: 'PROTEC.JIPIJAPA'.titleize)
Neightborhood.create!(city: quito, name: 'PUELLARO'.titleize)
Neightborhood.create!(city: quito, name: 'PUEMBO CABECERA'.titleize)
Neightborhood.create!(city: quito, name: 'PUERTAS DEL SOL'.titleize)
Neightborhood.create!(city: quito, name: 'QUITO SUR'.titleize)
Neightborhood.create!(city: quito, name: 'RANCHO ALTTO J.P'.titleize)
Neightborhood.create!(city: quito, name: 'RANCHO BAJO'.titleize)
Neightborhood.create!(city: quito, name: 'RANCHO S_ANTONIO'.titleize)
Neightborhood.create!(city: quito, name: 'RECREO CLEMENCIA'.titleize)
Neightborhood.create!(city: quito, name: 'RUPERTO ALARCON'.titleize)
Neightborhood.create!(city: quito, name: 'RUPERTO GORDO'.titleize)
Neightborhood.create!(city: quito, name: 'S CLARA S_MILAN'.titleize)
Neightborhood.create!(city: quito, name: 'S TERESITA ALTA'.titleize)
Neightborhood.create!(city: quito, name: 'S_AGUSTIN'.titleize)
Neightborhood.create!(city: quito, name: 'S_ANTONIO'.titleize)
Neightborhood.create!(city: quito, name: 'S_ANTONIO CONOCO'.titleize)
Neightborhood.create!(city: quito, name: 'S_BARTOLO'.titleize)
Neightborhood.create!(city: quito, name: 'S_CARLOS MULTIF'.titleize)
Neightborhood.create!(city: quito, name: 'S_CARLOS VENCEN'.titleize)
Neightborhood.create!(city: quito, name: 'S_CRISTOBAL'.titleize)
Neightborhood.create!(city: quito, name: 'S_ENRIQUE VELASC'.titleize)
Neightborhood.create!(city: quito, name: 'S_FELIPE'.titleize)
Neightborhood.create!(city: quito, name: 'S_FERNANDO'.titleize)
Neightborhood.create!(city: quito, name: 'S_JOSE DE MORAN'.titleize)
Neightborhood.create!(city: quito, name: 'S_JUAN'.titleize)
Neightborhood.create!(city: quito, name: 'S_JUAN ARMENIA'.titleize)
Neightborhood.create!(city: quito, name: 'S_JUAN TURUBAMBA'.titleize)
Neightborhood.create!(city: quito, name: 'S_LORENZO'.titleize)
Neightborhood.create!(city: quito, name: 'S_LUIS'.titleize)
Neightborhood.create!(city: quito, name: 'S_LUIS BAJO'.titleize)
Neightborhood.create!(city: quito, name: 'S_LUIS CALDERON'.titleize)
Neightborhood.create!(city: quito, name: 'S_MARTA MANGAHUA'.titleize)
Neightborhood.create!(city: quito, name: 'S_MARTIN PORRAS'.titleize)
Neightborhood.create!(city: quito, name: 'S_PEDRO CLAVEL'.titleize)
Neightborhood.create!(city: quito, name: 'S_PEDRO CLAVERI'.titleize)
Neightborhood.create!(city: quito, name: 'S_SALVADOR'.titleize)
Neightborhood.create!(city: quito, name: 'S_TOSPAMBA'.titleize)
Neightborhood.create!(city: quito, name: 'SAN  BLAS'.titleize)
Neightborhood.create!(city: quito, name: 'SAN ANTONIO'.titleize)
Neightborhood.create!(city: quito, name: 'SAN DIEGO'.titleize)
Neightborhood.create!(city: quito, name: 'SAN MARCOS'.titleize)
Neightborhood.create!(city: quito, name: 'SANTIAGO 1'.titleize)
Neightborhood.create!(city: quito, name: 'SENIOR DEL ARBOL'.titleize)
Neightborhood.create!(city: quito, name: 'SOLANDA'.titleize)
Neightborhood.create!(city: quito, name: 'SOLANDA S_ 3'.titleize)
Neightborhood.create!(city: quito, name: 'STA BARBARA ALTA'.titleize)
Neightborhood.create!(city: quito, name: 'STA.LUCIA ALTA'.titleize)
Neightborhood.create!(city: quito, name: 'STA.ROSA ARGELIA'.titleize)
Neightborhood.create!(city: quito, name: 'STA.ROSA SINGUNA'.titleize)
Neightborhood.create!(city: quito, name: 'STA_ANA'.titleize)
Neightborhood.create!(city: quito, name: 'STA_MARIA'.titleize)
Neightborhood.create!(city: quito, name: 'STO DGO ICHUB'.titleize)
Neightborhood.create!(city: quito, name: 'TACHINA 2'.titleize)
Neightborhood.create!(city: quito, name: 'TAMBILLO'.titleize)
Neightborhood.create!(city: quito, name: 'THOMAS'.titleize)
Neightborhood.create!(city: quito, name: 'TURUBA.MONJA BEV'.titleize)
Neightborhood.create!(city: quito, name: 'UNION NACIONAL'.titleize)
Neightborhood.create!(city: quito, name: 'UNIVERSI CENTRAL'.titleize)
Neightborhood.create!(city: quito, name: 'VALLE DEL SUR'.titleize)
Neightborhood.create!(city: quito, name: 'VENCEREMOS'.titleize)
Neightborhood.create!(city: quito, name: 'VERTIENTES SUR'.titleize)
Neightborhood.create!(city: quito, name: 'VILLA FLORA'.titleize)
Neightborhood.create!(city: quito, name: 'VIRGENPATA'.titleize)
Neightborhood.create!(city: quito, name: 'VISTA HERMOSA'.titleize)
Neightborhood.create!(city: quito, name: 'YARUQUI URB HIST'.titleize)